# halberd-latex.pl -- docs/HALBERD.tex for sim/halberd-gen.pl (required from there, not run on its own).
# The same content as docs/HALBERD.html, typeset for print: black and white, booktabs tables, pgfplots charts
# (solid / dashed / dotted lines and grey bars, never colour). Build the PDF with `perl sim/halberd-gen.pl --pdf`
# (needs XeLaTeX + latexmk; the kit's target laptop has neither, so docs/HALBERD.pdf is committed).
use strict;
use warnings;
use List::Util ();

sub _lx_tx {                                      # plain text -> LaTeX
    my $t = shift // '';
    $t =~ s/\\/\x01/g;
    $t =~ s/([&%\$#_{}])/\\$1/g;
    $t =~ s/~/\\textasciitilde{}/g;
    $t =~ s/\^/\\textasciicircum{}/g;
    $t =~ s/\x01/\\textbackslash{}/g;
    $t =~ s/(\d)--(\d)/$1--$2/g;
    $t =~ s/\.\.\./\\ldots{}/g;
    $t;
}
sub _lx_md { my $t = _lx_tx(shift); $t =~ s/\*\*(.+?)\*\*/\\textbf{$1}/g; $t }   # the doc's cells use **bold** only
sub _lx_c  { my $n = shift; 1 while $n =~ s/^(-?\d+)(\d{3})/$1,$2/; $n }
sub _lx_usd { my $v = sprintf '%.0f', shift; my $neg = $v < 0; $v = abs $v; 1 while $v =~ s/^(\d+)(\d{3})/$1,$2/; ($neg ? '$-$' : '') . "\\\$$v" }
sub _lx_date { my ($y, $m, $d) = split /-/, shift; my @mn = qw(January February March April May June July August September October November December); sprintf '%d %s %d', $d, $mn[ $m - 1 ], $y }

sub _lx_plot_lines {                              # [ [legend, style, [values]] ], x tick labels
    my ($labels, $series, %o) = @_;
    my $n = @$labels;
    my $ticks = join ',', grep { $_ % 2 == 0 || $_ == $n - 1 } 0 .. $n - 1;
    my $tl = join ',', map { "{$labels->[$_]}" } grep { $_ % 2 == 0 || $_ == $n - 1 } 0 .. $n - 1;
    my $s = "\\begin{tikzpicture}\n\\begin{axis}[halberdplot, width=$o{width}, height=$o{height}, xtick={$ticks}, xticklabels={$tl}"
          . ($o{ylabel} ? ", ylabel={$o{ylabel}}" : '') . ($o{money} ? ', scaled y ticks=false, yticklabel style={/pgf/number format/.cd, fixed, precision=0, 1000 sep={\\mbox{,}}}, ymin=0, yticklabel={\\$\\pgfmathprintnumber{\\tick}}' : '')
          . ", legend columns=" . scalar(@$series) . "]\n";
    for my $sr (@$series) {
        my ($name, $style, $v) = @$sr;
        $s .= "\\addplot[$style] coordinates {" . join(' ', map { sprintf '(%d,%.1f)', $_, $v->[$_] } 0 .. $#$v) . "};\n\\addlegendentry{$name}\n";
    }
    "$s\\end{axis}\n\\end{tikzpicture}\n";
}

sub halberd_latex {
    my ($file, %a) = @_;
    my ($days, $sprints, $plan, $seg, $rows, $es) = @a{qw(days sprints plan seg journal_rows evm_series)};
    my @order = qw(E V B T G M L);
    my (%seg_pts, %seg_tasks, %first, %last);
    for my $p (@$plan) { for my $t (@{ $p->{tasks} }) { $seg_pts{ $t->{seg} } += $t->{pts}; $seg_tasks{ $t->{seg} }++ } }
    for my $d (@$days) { $first{ $d->{seg} } //= $d->{date}; $last{ $d->{seg} } = $d->{date} }
    my @left = (1960); push @left, $left[-1] - $_->{done} for @$sprints;

    my $o = <<'PRE';
% Generated by sim/halberd-gen.pl (sim/halberd-latex.pl). Edit the doc or the generator, not this file.
% Build: perl sim/halberd-gen.pl --pdf   (XeLaTeX + latexmk)
\documentclass[12pt,letterpaper,oneside]{article}
\usepackage[margin=1in,headheight=14pt]{geometry}
\usepackage{fontspec}
\setmainfont{LibertinusSerif}[Extension=.otf,UprightFont=*-Regular,BoldFont=*-Bold,ItalicFont=*-Italic,BoldItalicFont=*-BoldItalic]
\setsansfont{LibertinusSans}[Extension=.otf,UprightFont=*-Regular,BoldFont=*-Bold,ItalicFont=*-Italic,BoldItalicFont=*-Bold]
\setmonofont{DejaVu Sans Mono}[Scale=0.80]
\usepackage{microtype}
\usepackage{booktabs,longtable,array,tabularx}
\usepackage{xcolor}
\usepackage{pgfplots}
\pgfplotsset{compat=1.17}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{caption}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyvrb}
\usepackage{float}
\usepackage{pdfpages}
\titleformat{\section}{\Large\bfseries}{\thesection}{0.8em}{}[\vspace{2pt}\titlerule]
\titleformat{\subsection}{\large\bfseries}{\thesubsection}{0.7em}{}
\titlespacing*{\section}{0pt}{18pt}{8pt}
\pagestyle{fancy}\fancyhf{}
\fancyhead[L]{\small IAMD MBSE SysEng Integration Into DevSecOps\enspace\textperiodcentered\enspace Notional Plan}
\fancyhead[R]{\small\thepage}
\fancyfoot[C]{\footnotesize\itshape Notional: every name and number is made up.}
\renewcommand{\headrulewidth}{0.4pt}
\setlength{\parindent}{0pt}\setlength{\parskip}{5pt}
\DeclareCaptionFont{figfont}{\fontsize{9}{11}\selectfont}
\captionsetup{font=figfont,labelfont=bf,skip=4pt}
\pgfplotsset{halberdplot/.style={axis lines=left, grid=major, grid style={gray!25, very thin},
  tick label style={font=\figfont}, label style={font=\figfont}, legend style={font=\figfont, draw=none, fill=none,
  at={(0.5,1.02)}, anchor=south}, every axis plot/.append style={line width=0.9pt, mark size=1.2pt}}}
\newcommand{\blk}{\textsuperscript{\dag}}
\newcommand{\figfont}{\fontsize{9}{11}\selectfont}   % tables and figures: 9pt
\begin{document}
PRE

    # ---- title page
    $o .= "\\IfFileExists{TheWheelCoverBW.pdf}{\\includepdf[pages=1,fitpaper=false,noautoscale=false,pagecommand={\\thispagestyle{empty}}]{TheWheelCoverBW.pdf}}{}\n"   # the binder's cover, black and white
        if $a{cover};
    $o .= <<'TITLE';
\begin{titlepage}
\centering
\vspace*{1.6in}
{\fontsize{30}{36}\selectfont\bfseries IAMD MBSE SysEng Integration\\[4pt] Into DevSecOps\par}
\vspace{10pt}
{\fontsize{22}{26}\selectfont\scshape Notional Plan\par}
\vspace{14pt}
{\Large Halberd: a 12-week SysML v1 to v2 port,\\ run on the agile kit\par}
\vspace{28pt}
\rule{0.55\textwidth}{0.4pt}\par
\vspace{14pt}
{\large Backlog, daily stand-ups, sprint burn-downs,\\ funding and earned value\par}
\vspace{1.2in}
\begin{minipage}{0.72\textwidth}\small\centering
Halberd is fictional and notional, and so is every number here. It is the kit's worked example: one solutions
architect ports a legacy SysML v1 model to SysML v2 text under a DevSecOps pipeline, 5 October to 23 December 2026.
\end{minipage}
\vfill
{\small Generated by \texttt{sim/halberd-gen.pl} from \texttt{docs/src/status-metrics.md}\par}
\end{titlepage}
\tableofcontents
\clearpage
TITLE

    # ---- overview
    $o .= "\\section{The program}\n";
    $o .= "Halberd's legacy SysML v1 model holds 1,960 in-scope items across seven organizations, and 1,450 DOORS requirements. "
        . "One solutions architect ports it to SysML v2 text, one segment at a time, starting Monday 5 October 2026: two-week sprints, "
        . "a baseline tagged every four weeks, and a stand-up every working day. The status meeting hears the alphabet: the 26 metrics "
        . "A--Z of \\texttt{docs/STATUS-METRICS.html}. Thanksgiving and 24--25 December are holidays, so the port runs 56 working days.\n\n";
    $o .= "Everything here is computed by the kit, not typed. The project is a real kit project, built by compiling one stand-up file per "
        . "day through the kit's own ledger; rebuild it and this document with one command:\n";
    $o .= "\\begin{Verbatim}[fontsize=\\figfont,frame=lines,framesep=6pt]\n"
        . "perl sim/halberd-gen.pl --pdf                          # data/halberd, docs/HALBERD.html and .pdf\n"
        . "perl bin/ledger.pl -f data/halberd/scrum.txt bal Sprint:3   # the ledger: 330 items done in sprint 3\n"
        . "perl agile.pl --today 2026-11-05 data/halberd          # the cockpit on a blocked day\n"
        . "\\end{Verbatim}\n";

    # ---- backlog
    $o .= "\\section{Backlog}\nThe tome is \\emph{Halberd SysML v2 port}; its epics are the seven segments, in the order they are ported. "
        . "Each task ports one day's worth of v1 items, counted in items (the journal's unit). A carried task counts in the segment being "
        . "worked when it was committed; the rows add up to all 1,960 items.\n\n";
    $o .= "\\begin{table}[H]\\centering\\figfont\n\\begin{tabular}{\@{}l l r r l\@{}}\n\\toprule\nEpic & Segment & v1 items & Tasks & Worked \\\\\n\\midrule\n";
    for my $k (@order) {
        $o .= sprintf "%s & %s & %s & %d & %s -- %s \\\\\n", $k, _lx_tx($seg->{$k}), _lx_c($seg_pts{$k} // 0), $seg_tasks{$k} // 0, substr($first{$k}, 5), substr($last{$k}, 5);
    }
    $o .= sprintf "\\midrule\n & \\textbf{Total} & \\textbf{%s} & \\textbf{%d} & \\\\\n\\bottomrule\n\\end{tabular}\n\\caption{Segments as epics.}\n\\end{table}\n",
        _lx_c(1960), List::Util::sum(map { $seg_tasks{$_} // 0 } @order);

    # ---- release
    $o .= "\\section{Release burn-down}\n";
    $o .= "\\begin{figure}[H]\\centering\n\\begin{tikzpicture}\n\\begin{axis}[halberdplot, ybar, bar width=20pt, width=0.85\\textwidth, height=5.2cm, "
        . "ymin=0, enlarge x limits=0.08, symbolic x coords={Start,S1,S2,S3,S4,S5,S6}, xtick=data, nodes near coords, "
        . "every node near coord/.append style={font=\\figfont}, ylabel={v1 items left}, axis lines*=left, ymajorgrids]\n"
        . "\\addplot[fill=gray!55, draw=black, line width=0.4pt] coordinates {"
        . join(' ', map { "(" . ($_ == 0 ? 'Start' : "S$_") . ",$left[$_])" } 0 .. $#left) . "};\n\\end{axis}\n\\end{tikzpicture}\n"
        . "\\caption{The whole v1 list, sprint by sprint.}\n\\end{figure}\n";
    $o .= "\\begin{table}[H]\\centering\\figfont\n\\begin{tabular}{\@{}c l r r r r r\@{}}\n\\toprule\nSprint & Dates & Committed & Done & Carried & Done \\% (X) & Items left \\\\\n\\midrule\n";
    for my $i (0 .. $#$sprints) {
        my ($sp, $r) = ($sprints->[$i], $rows->[$i]);
        my @sd = grep { $_->{sprint} == $sp->{n} } @$days;
        $o .= sprintf "%d & %s -- %s & %d & %d & %d & %d & %s \\\\\n", $sp->{n}, substr($sd[0]{date}, 5), substr($sd[-1]{date}, 5), @{$r}{qw(committed done carryover pct)}, _lx_c($left[ $i + 1 ]);
    }
    $o .= "\\bottomrule\n\\end{tabular}\n\\caption{Sprint totals, computed from the compiled journal by \\texttt{Scrum::sprint\\_summary}; the generator stops if any differs from the doc.}\n\\end{table}\n";

    # ---- money
    if ($es) {
        my @lab = map { $_->{label} } @$es;
        my $tot = sub { my $k = shift; [ map { $_->{evm}{total}{$k} // 0 } @$es ] };
        $o .= "\\section{Funding and earned value}\n";
        $o .= "A notional FY27 funding journal sits beside the stand-up journal, in the same ledger format "
            . "(\\texttt{data/halberd/funding.ledger}). Each segment is budgeted at a notional \\\$150 per v1 item, time-phased over the days the plan "
            . "works it. " . _lx_usd($a{authorized}) . " is authorized on 1 October: the budget at completion of " . _lx_usd($a{bac})
            . " plus a 10\\% reserve. Labor posts weekly from the items actually ported; sprint 3 overran while it waited on the shared runner. "
            . "Percent complete comes from the stand-ups, so earned value is computed, not estimated.\n\n";
        $o .= "\\begin{figure}[H]\\centering\n" . _lx_plot_lines(\@lab, [ [ 'Planned (BCWS)', 'black, dashed', $tot->('bcws') ], [ 'Earned (BCWP)', 'black, mark=*', $tot->('bcwp') ], [ 'Actual (ACWP)', 'black, densely dotted, mark=square*', $tot->('acwp') ] ],
            width => '0.92\\textwidth', height => '6.2cm', money => 1) . "\\caption{Cumulative cost at the end of each week.}\n\\end{figure}\n";
        $o .= "\\begin{figure}[H]\\centering\n" . _lx_plot_lines(\@lab, [ [ 'Funds remaining', 'black, mark=o', [ map { $_->{funds} } @$es ] ] ],
            width => '0.92\\textwidth', height => '5cm', money => 1) . "\\caption{Funds remaining at the end of each week.}\n\\end{figure}\n";
        my @months = grep { my $i = $_; $i == $#$es || substr($es->[$i]{date}, 0, 7) ne substr($es->[ $i + 1 ]{date}, 0, 7) } 0 .. $#$es;
        my %ord = (E => 1, V => 2, B => 3, T => 4, G => 5, M => 6, L => 7);
        for my $i (@months) {
            my $e = $es->[$i]{evm};
            $o .= "\\subsection{Earned value at " . _lx_date($es->[$i]{date}) . "}\n";
            $o .= "{\\figfont\\setlength{\\tabcolsep}{3pt}\n\\begin{tabular}{\@{}l r r r r r r r r r r\@{}}\n\\toprule\n"
                . "Segment & Done & BAC & BCWS & BCWP & ACWP & CV & SV & CPI & SPI & EAC \\\\\n\\midrule\n";
            for my $r ((sort { ($ord{ substr($a->{account}, -1) } // 9) <=> ($ord{ substr($b->{account}, -1) } // 9) } @{ $e->{rows} }), $e->{total}) {
                my $tot_row = $r->{account} !~ /:(\w)$/;
                my $name = $tot_row ? "\\midrule\n\\textbf{Total}" : "$1 " . _lx_tx($seg->{$1});
                $o .= sprintf "%s & %.0f\\%% & %s & %s & %s & %s & %s & %s & %s & %s & %s \\\\\n", $name, 100 * ($r->{pct} // 0),
                    (map { defined $r->{$_} ? _lx_usd($r->{$_}) : '--' } qw(bac bcws bcwp acwp cv sv)),
                    defined $r->{cpi} ? sprintf('%.2f', $r->{cpi}) : '--', defined $r->{spi} ? sprintf('%.2f', $r->{spi}) : '--', defined $r->{eac} ? _lx_usd($r->{eac}) : '--';
            }
            $o .= "\\bottomrule\n\\end{tabular}}\n\n";
            my $f = $es->[$i]{forecast};
            $o .= sprintf("Funds remaining %s; average burn over the last two months %s a month; at that rate the money lasts %.1f more months (to %s).\n\n",
                _lx_usd($f->{balance}), _lx_usd($f->{burn}), $f->{months} // 0, $f->{runout} // '--') if $f && $f->{burn} > 0 && ($e->{total}{pct} // 0) < 1;
        }
        my $last = $es->[-1];
        $o .= sprintf "\\textbf{At the finish:} %s spent against a %s budget (CPI %.2f); %s of the %s authorized is left, so the overrun came out of the reserve.\n\n",
            _lx_usd($last->{evm}{total}{acwp}), _lx_usd($a{bac}), $last->{evm}{total}{cpi}, _lx_usd($last->{funds}), _lx_usd($a{authorized});
        $o .= "{\\figfont\\itshape CPI = earned / actual (above 1 is under cost); SPI = earned / planned (above 1 is ahead); EAC = BAC / CPI. "
            . "The same numbers come from \\texttt{bin/ledger.pl evm} and \\texttt{forecast}.\\par}\n";
    }

    # ---- sprints and stand-ups
    $o .= "\\section{Sprints and daily stand-ups}\nEach stand-up answers yesterday, today and blockers, in the alphabet of the A--Z metrics. "
        . "A dagger\\blk{} marks a blocked day.\n";
    for my $p (@$plan) {
        my $sp = $p->{sprint}; my @sd = @{ $p->{days} };
        my @act = ($sp->{committed}); my $cum = 0;
        push @act, $sp->{committed} - ($cum += $_->{ported}) for @sd;
        $act[-1] = $sp->{carried};
        my @ideal = map { $sp->{committed} * (1 - $_ / @sd) } 0 .. @sd;
        $o .= sprintf "\\clearpage\n\\subsection{Sprint %d: %s to %s}\nCommitted %d. Done %d. Carried over %d. Done %d\\%% (X).%s\n\n",
            $sp->{n}, _lx_date($sd[0]{date}), _lx_date($sd[-1]{date}), @{$sp}{qw(committed done carried pct)},
            $p->{carry_in} ? " Includes $p->{carry_in}{id}, $p->{carry_in}{pts} items carried in from sprint " . ($sp->{n} - 1) . '.' : '';
        $o .= "\\begin{center}\n" . _lx_plot_lines([ 'Start', map { $_->{label} } @sd ], [ [ 'Actual', 'black, mark=*', \@act ], [ 'Ideal', 'black, dashed', \@ideal ] ],
            width => '0.8\\textwidth', height => '4.6cm', ylabel => 'Committed items left') . "\\end{center}\n";
        $o .= "{\\figfont\\setlength{\\tabcolsep}{4pt}\\renewcommand{\\arraystretch}{1.15}\n"
            . "\\begin{longtable}{\@{}>{\\raggedright}p{0.075\\textwidth} r r >{\\raggedright}p{0.34\\textwidth} >{\\raggedright}p{0.22\\textwidth} >{\\raggedright\\arraybackslash}p{0.17\\textwidth}\@{}}\n"
            . "\\toprule\nDay & Ported & Left & Yesterday & Today & Blockers \\\\\n\\midrule\n\\endhead\n\\bottomrule\n\\endfoot\n";
        for my $d (@sd) {
            my $blk = $d->{b} !~ /^None\.?$/;
            $o .= sprintf "%s %s%s & %d & %s & %s & %s & %s \\\\\n", $d->{dow}, $d->{label}, $blk ? '\\blk' : '', $d->{ported}, _lx_c($d->{left}), _lx_md($d->{y}), _lx_md($d->{t}), $blk ? _lx_md($d->{b}) : '--';
        }
        $o .= "\\end{longtable}}\n";
    }
    $o .= "\\end{document}\n";
    open my $fh, '>:encoding(UTF-8)', $file or die "cannot write $file: $!\n";
    print $fh $o; close $fh or die "cannot write $file: $!\n";
}
1;
