#!/usr/bin/perl
# Simulates two years (52 two-week sprints) of real journal history for 10 teams,
# by generating real stand-up verb files and compiling them through the actual,
# tested Standup.pm/Scrum.pm pipeline -- not hand-rolled fake ledger text. That
# guarantees the resulting journal is valid and that every number in HISTORY.html
# (velocity, predictability, blockers, load) is computed by the same code that
# runs in production, not a separate approximation.
#
# Standalone planning/reporting tool -- not part of the tested kit (lib/, bin/,
# tests/). Pure core Perl, no CPAN.
#
# Usage:  perl sim/history-gen.pl [--dir PATH] [--sprints N] [--seed N]
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Getopt::Long;
use Time::Local qw(timegm);
use Prelude qw(sorted sum);
use Standup qw(parse_standup apply);
use Scrum   qw(load items sprint_summary velocity blocked brief_status);

my %o = (dir => "$FindBin::Bin/../data/history", sprints => 52, seed => 7);   # project data lives in data/<project>/, one git repo each, ignored by the kit's repo
GetOptions(\%o, 'dir=s', 'sprints=i', 'seed=i') or exit 2;
srand($o{seed});

mkdir $o{dir} unless -d $o{dir};
my $journal = "$o{dir}/scrum.txt";
open my $fh, '>', $journal or die "cannot write $journal: $!\n";
print $fh "; generated by sim/history-gen.pl -- $o{sprints} simulated sprints, seed $o{seed}\n";
close $fh;

# ---- date arithmetic: sprints start Wednesday, run 14 days (per docs/WORKFLOW.html #3)
sub ymd    { my @t = gmtime(shift); sprintf '%04d-%02d-%02d', $t[5] + 1900, $t[4] + 1, $t[3] }
sub add_days { my ($epoch, $n) = @_; $epoch + $n * 86400 }
my $start = timegm(0, 0, 12, 24, 8, 2024 - 1900);   # 2024-09-24, a Wednesday -- ~2 years before "today" in this kit's fixtures

# ---- the world being simulated
my @teams = qw(Alpha Bravo Charlie Delta Echo Foxtrot Golf Hotel India Juliet);
my %code  = (Alpha=>'ALPH', Bravo=>'BRAV', Charlie=>'CHAR', Delta=>'DELT', Echo=>'ECHO',
             Foxtrot=>'FOXT', Golf=>'GOLF', Hotel=>'HOTL', India=>'INDI', Juliet=>'JULI');
my %tome_of = (Auth=>'Platform', Ops=>'Platform', Onboarding=>'Platform', Reporting=>'Insights', Billing=>'Insights');
my @epics = keys %tome_of;
my @pts_choices = (2, 3, 5, 8);
my %idn; my %backlog; my %carry;              # per-team: next id number, in-flight backlog [{id,points}], carried ids [id,...]
$idn{$_} = 1, $backlog{$_} = [], $carry{$_} = [] for @teams;

sub maturity { my $k = shift; 0.55 + 0.37 * ($k - 1) / ($o{sprints} - 1) }   # ramps 0.55 -> 0.92 across the run: the team getting better at estimating/delivering
sub capacity { my $k = shift; 30 + int($k / 8) + int(rand(5)) - 2 }         # slow capacity growth + noise, never below ~24

my @history;
my $s;
for my $k (1 .. $o{sprints}) {
    my $plan_date  = ymd(add_days($start, ($k - 1) * 14));
    my $close_date = ymd(add_days($start, ($k - 1) * 14 + 13));
    my $mat = maturity($k);

    # ---- planning day: cap, replenish backlog, commit carryover + new work up to ~108% load
    my $plan_text = "$plan_date\nsprint $k\n";
    for my $team (@teams) {
        my $cap = capacity($k);
        $plan_text .= "== $team\ncap $cap\n";
        my @lines;
        my $backlog_sum = sum(map { $_->{points} } @{ $backlog{$team} }) || 0;
        while ($backlog_sum < $cap * 1.5) {
            my $pts   = $pts_choices[ int(rand(@pts_choices)) ];
            my $epic  = $epics[ int(rand(@epics)) ];
            my $id    = "$code{$team}-" . $idn{$team}++;
            my $owner = "$team-" . (1 + int(rand(10)));
            push @lines, "new $id $pts Story $id p:" . (1 + int(rand(3))) . " e:$epic t:$tome_of{$epic} o:$owner";
            push @{ $backlog{$team} }, { id => $id, points => $pts };
            $backlog_sum += $pts;
        }
        my $committed_sum = 0;
        for my $c (@{ $carry{$team} }) { push @lines, "commit $c->{id}"; $committed_sum += $c->{points} }   # carryover is recommitted first and counts against capacity
        $carry{$team} = [];
        my @keep;                                 # commit what fits; the overcommit ceiling falls from 110% to 100% as the teams learn to stop overcommitting
        my $ceiling = 1.10 - 0.10 * ($k - 1) / ($o{sprints} - 1);
        for my $it (@{ $backlog{$team} }) {
            if ($committed_sum < $cap * 0.95 && $committed_sum + $it->{points} <= $cap * $ceiling) { push @lines, "commit $it->{id}"; $committed_sum += $it->{points} }
            else { push @keep, $it }
        }
        $backlog{$team} = \@keep;
        $plan_text .= join('', map { "$_\n" } @lines);
    }
    my $su = parse_standup($plan_text);
    die "planning sprint $k: " . join('; ', @{ $su->{errors} }) . "\n" if @{ $su->{errors} };
    $s //= load($journal, today => $plan_date);   # first sprint only; afterwards $s is the post-close state of the previous sprint, which is exactly the pre-planning state of this one
    apply($s, $su, $journal);

    # ---- two weeks pass: reload, decide done/carry/block per item using this sprint's maturity
    $s = load($journal, today => $close_date);
    my $close_text = "$close_date\nsprint $k\n";
    my $p_block = 0.18 * (1 - $mat);              # blockers get rarer as the teams mature: ~8% of carried items early, ~1.5% by the end
    for my $team (@teams) {
        my @committed = items($s, state => 'committed', sprint => $k, team => $team);
        my (@done, @carry_now, @block);
        for my $it (@committed) {
            my $p = $mat - 0.02 * (($it->{points} // 5) - 3) + (rand(0.2) - 0.1);   # smaller items finish slightly more reliably
            if (rand() < $p) { push @done, $it->{id} }
            else {
                push @carry_now, { id => $it->{id}, points => $it->{points} };
                push @block, $it->{id} if rand() < $p_block;
            }
        }
        $close_text .= "== $team\n";
        $close_text .= 'done ' . join(' ', @done) . "\n" if @done;
        $close_text .= 'carry ' . join(' ', map { $_->{id} } @carry_now) . "\n" if @carry_now;
        $close_text .= "block $_ waiting on dependency\n" for @block;
        $carry{$team} = \@carry_now;
    }
    $su = parse_standup($close_text);
    die "close sprint $k: " . join('; ', @{ $su->{errors} }) . "\n" if @{ $su->{errors} };
    apply($s, $su, $journal);

    # ---- snapshot: what would actually have been reported at this sprint's review (and the state the next planning starts from)
    $s = load($journal, today => $close_date);
    my $r  = sprint_summary($s, $k);
    my $v  = velocity($s);
    my ($level, $headline) = brief_status($s, $k);
    push @history, {
        sprint => $k, plan_date => $plan_date, close_date => $close_date, level => $level, headline => $headline,
        totals => $r->{totals}, teams => $r->{teams}, velocity_avg => $v->{avg},
        blocked => [ blocked($s) ],
    };
    print "sprint $k/$o{sprints}  $close_date  [$level]  $r->{totals}{pct}% done, $r->{totals}{committed} committed\n";
}

print "\nwrote $journal (" . (-s $journal) . " bytes)\n";

# ---- render HISTORY.html, marked from the project's scrum.conf when there is one (banner, marking_* fields)
my %marking;
if (open my $cf, '<', "$o{dir}/scrum.conf") {
    while (<$cf>) { s/\s*[#;].*$//; $marking{$1} = $2 if /^\s*(\w+)\s*=\s*(.*?)\s*$/ }
    close $cf;
}
require "$FindBin::Bin/history-render.pl";
history_render(\@history, "$o{dir}/HISTORY.html", { teams => \@teams, sprints => $o{sprints}, seed => $o{seed}, marking => \%marking });
print "wrote $o{dir}/HISTORY.html\n";
