#!/usr/bin/perl
# status-metrics-qrg.pl -- docs/STATUS-METRICS-QRG.tex (and with --pdf, .pdf): the A-Z status metrics on one sheet of
# Letter paper, printed both sides. Front: the 26 metrics in their six groups, each with its report phrases and its goal.
# Back: how to report -- the round-robin, what the status words mean, what moves which letter, the dashboard, the commands.
#
# Read from the same sources as the full doc, so the card cannot drift from it: the metric names, phrases, groups,
# round-robin and translation key from docs/src/status-metrics.md; each metric's direction and target from the
# dashboard's definitions (docs/STATUS-DASHBOARD.html). Black and white; the group markers match the dashboard's.
#
# Standalone tool -- not part of the tested kit. Core Perl. --pdf needs XeLaTeX + latexmk (not on the target laptop,
# so the PDF is committed).
#
# Usage:  perl sim/status-metrics-qrg.pl [--doc FILE] [--dash FILE] [--tex FILE] [--pdf]
use strict;
use warnings;
use FindBin;
use Getopt::Long;

my $ROOT = "$FindBin::Bin/..";
my %o = (doc => "$ROOT/docs/src/status-metrics.md", dash => "$ROOT/docs/STATUS-DASHBOARD.html", tex => "$ROOT/docs/STATUS-METRICS-QRG.tex");
GetOptions(\%o, 'doc=s', 'dash=s', 'tex=s', 'pdf') or exit 2;

sub slurp { my $f = shift; open my $fh, '<:encoding(UTF-8)', $f or die "cannot read $f: $!\n"; local $/; my $t = <$fh>; close $fh; $t }
sub tx {                                       # text -> LaTeX
    my $t = shift // '';
    $t =~ s/\\/\x01/g;
    $t =~ s/([&%\$#_{}])/\\$1/g;
    $t =~ s/~/\\textasciitilde{}/g;
    $t =~ s/\x01/\\textbackslash{}/g;
    $t =~ s/\[N\]/\\N{}/g;                     # the count slot, set as a small box
    $t =~ s/"([^"]*)"/\x{201C}$1\x{201D}/g;
    $t =~ s/(?<=\w)'(?=\w)/\x{2019}/g;
    $t;
}

# ---- the doc: groups, metrics and phrases (top part only), round-robin, translation key
my $md = slurp($o{doc});
my ($top) = $md =~ /^(.*?)^# Appendix A/ms or die "$o{doc}: no Appendix A heading\n";
my ($frame) = $top =~ /^Frame:\s*(.+)$/m;
my (@groups, $g, $m);
for my $l (split /\n/, $top) {
    if ($l =~ /^## (.+)$/ && $1 !~ /^Round-robin/) { push @groups, $g = { name => $1, metrics => [] }; next }
    if ($l =~ /^## Round-robin/) { $g = undef; next }
    if ($g && $l =~ /^([A-Z])\. \*\*(.+?)\*\*/) { push @{ $g->{metrics} }, $m = { L => $1, name => $2, phrases => [] }; next }
    if ($g && $m && $l =~ /^\s+-\s+"?(.+?)"?\s*$/) { push @{ $m->{phrases} }, $1 }
}
my $n = 0; $n += @{ $_->{metrics} } for @groups;
@groups == 6 && $n == 26 or die "$o{doc}: expected 6 groups and 26 metrics, found " . @groups . " and $n\n";
my ($rr) = $top =~ /^## Round-robin template\s+"?(.+?)"?\s*$/m or die "$o{doc}: no round-robin template\n";
my ($key) = $md =~ /^## Translation key\s*\n(.*?)\n\n/ms or die "$o{doc}: no translation key\n";
my @key = map { [ map { s/^\s+|\s+$//gr } (split /\|/)[ 1 .. 3 ] ] } grep { /^\|/ && !/^\|\s*-/ && !/What I did/ } split /\n/, $key;

# ---- the dashboard: direction and target per letter
my $dash = slurp($o{dash});
my %goal;
while ($dash =~ /^([A-Z]):\{n:"[^"]*",f:"([^"]*)",dir:"(\w+)"(?:,t:("?)([^,"]*)\4)?/mg) {
    my ($L, $fmt, $dir, $t) = ($1, $2, $3, $5);
    my ($unit) = $fmt =~ /\{v\}\s*(%|h\b|min\b|d\b)/;
    $unit //= '';
    my $u = $unit eq '%' ? '\%' : $unit ? "\\,$unit" : '';
    $goal{$L} = $dir eq 'info' ? 'tracked'
              : $dir eq 'zero' ? 'none reach integration'
              : !defined $t     ? ($dir eq 'up' ? 'higher is better' : 'lower is better')
              : $t eq 'total'   ? 'goal: all'
              : $dir eq 'up'    ? ($t == 100 && $unit eq '%' ? 'goal 100\%' : 'goal $\\geq$ ' . "$t$u")
              : $t == 0         ? 'goal 0'
              :                   'goal $\\leq$ ' . "$t$u";
}
keys %goal == 26 or die "$o{dash}: found targets for " . keys(%goal) . " metrics, expected 26\n";

# ---- the card
my @mark = ('\\ding{110}', '\\ding{108}', '\\ding{115}', '\\ding{117}', '\\ding{58}', '\\ding{72}');   # square circle triangle diamond cross star: the dashboard's markers
my $t = <<'PRE';
% Generated by sim/status-metrics-qrg.pl from docs/src/status-metrics.md and docs/STATUS-DASHBOARD.html. Edit those, not this.
% Build: perl sim/status-metrics-qrg.pl --pdf   (XeLaTeX + latexmk)
\documentclass[letterpaper]{article}
\usepackage[margin=0.4in,top=0.35in,bottom=0.35in]{geometry}
\usepackage{fontspec}
\setmainfont{LibertinusSerif}[Extension=.otf,UprightFont=*-Regular,BoldFont=*-Bold,ItalicFont=*-Italic,BoldItalicFont=*-BoldItalic]
\setsansfont{LibertinusSans}[Extension=.otf,UprightFont=*-Regular,BoldFont=*-Bold,ItalicFont=*-Italic,BoldItalicFont=*-Bold]
\setmonofont{DejaVu Sans Mono}[Scale=0.80]
\usepackage{microtype,multicol,booktabs,tabularx,array,pifont,xcolor,enumitem}
\usepackage[hidelinks]{hyperref}
\pagestyle{empty}
\setlength{\parindent}{0pt}\setlength{\parskip}{0pt}
\setlength{\columnsep}{0.22in}\setlength{\columnseprule}{0.3pt}
\raggedcolumns
\newcommand{\N}{\fbox{\scriptsize N}}\setlength{\fboxsep}{0.6pt}
\newcommand{\grp}[2]{\par\vspace{4pt}{\sffamily\bfseries\large #1\enspace #2}\par\vspace{1pt}\hrule height 0.8pt\vspace{3pt}}
\newcommand{\metric}[4]{\par\vspace{2.5pt}\noindent\makebox[1.25em][l]{\sffamily\bfseries #1}\textbf{#2}\hfill{\sffamily\scriptsize #3}\par
  \vspace{0.5pt}{\leftskip=1.25em\small\itshape #4\par}}
\newcommand{\head}[1]{\par\vspace{7pt}{\sffamily\bfseries\large #1}\par\vspace{1pt}\hrule\vspace{4pt}}
\begin{document}
\fontsize{10}{12}\selectfont
PRE
$t .= "{\\sffamily\\bfseries\\LARGE Status metrics A--Z}\\hfill{\\sffamily\\large quick reference}\\par\\vspace{3pt}\n\\hrule height 1.2pt\\vspace{4pt}\n";
$t .= "{\\small Frame: \\emph{" . tx($frame =~ s/^"|"$//gr) . "}\\quad Report the outcome and the count; every \\N{} comes from its collection method "
    . "(Appendix A of \\texttt{docs/STATUS-METRICS.html}). The marker beside each group is the dashboard's, so a black-and-white print still tells them apart.}\\par\n";
$t .= "\\begin{multicols}{2}\n";
for my $i (0 .. $#groups) {
    my $gr = $groups[$i];
    $t .= "\\grp{$mark[$i]}{" . tx($gr->{name}) . "}\n";
    for my $mt (@{ $gr->{metrics} }) {
        $t .= sprintf "\\metric{%s}{%s}{%s}{%s}\n", $mt->{L}, tx($mt->{name}), $goal{ $mt->{L} },
            join('\\\\ ', map { tx($_) } @{ $mt->{phrases} });
    }
}
$t .= "\\end{multicols}\n\\newpage\n";

# back: how to report
$t .= "{\\sffamily\\bfseries\\LARGE Reporting with A--Z}\\hfill{\\sffamily\\large quick reference}\\par\\vspace{3pt}\n\\hrule height 1.2pt\\vspace{2pt}\n";
$t .= "\\begin{multicols}{2}\n";
$t .= "\\head{The round-robin, in the status meeting}\nPick the three or four letters that moved; say each as its phrase, outcome first, count second, then what comes next:\\par\\vspace{3pt}\n"
    . "{\\leftskip=1em\\rightskip=1em\\itshape " . tx($rr) . "\\par}\n\\vspace{3pt}\n"
    . "\\begin{itemize}[leftmargin=1.1em,itemsep=1pt,topsep=2pt]\n"
    . "\\item One letter, one sentence. Never a number without its letter, never a letter without its number.\n"
    . "\\item Say what moved since last time; a metric that did not move is not news.\n"
    . "\\item Bad news is a letter too: say it plainly (F orphans, Y blocked days) with the owner and the next step.\n"
    . "\\item Every \\N{} must be reproducible from the repo or its exports by the command in Appendix A.\n"
    . "\\end{itemize}\n";
$t .= "\\head{What the status words mean}\n\\begin{tabularx}{\\linewidth}{\@{}>{\\sffamily\\bfseries}l X\@{}}\n"
    . "on target & At or past its goal (the goal is on the front, beside each metric).\\\\\n"
    . "improving & Not at its goal yet, but better than last time.\\\\\n"
    . "act & Not at its goal and not getting better: name an owner and a step.\\\\\n"
    . "tracking & No goal (D, J, U): report the trend.\\\\\n"
    . "no data & Nothing collected yet (W before the first broken gate).\\\\\n"
    . "\\end{tabularx}\n";
$t .= "\\head{The six groups, in one breath}\n\\begin{tabularx}{\\linewidth}{\@{}l>{\\bfseries}l X\@{}}\n";
my @why = ('How much of the model is in the pipeline yet?', 'Is what is there correct and traceable?', 'What does it save against the old document process?',
           'Do analysis and simulation draw on the model?', 'What security and configuration risk has the pipeline closed?', 'Is the team delivering steadily?');
$t .= "$mark[$_] & " . tx($groups[$_]{name}) . " (" . join('', map { $_->{L} } @{ $groups[$_]{metrics} }) . ") & $why[$_]\\\\\n" for 0 .. $#groups;
$t .= "\\end{tabularx}\n";
$t .= "\\columnbreak\n";
$t .= "\\head{What moves which letter}\n{\\small\\begin{tabularx}{\\linewidth}{\@{}>{\\raggedright\\arraybackslash}X >{\\sffamily\\bfseries}l >{\\raggedright\\arraybackslash}X\@{}}\n\\toprule\nWhat I did & Moves & What I say\\\\\n\\midrule\n";
$t .= join('', map { tx($_->[0]) . " & " . tx($_->[1]) . " & " . tx($_->[2]) . "\\\\\n" } @key);
$t .= "\\bottomrule\n\\end{tabularx}}\n";
$t .= "\\head{The dashboard}\n\\begin{enumerate}[leftmargin=1.2em,itemsep=1pt,topsep=2pt]\n"
    . "\\item Open \\texttt{docs/STATUS-DASHBOARD.html} (one file, works offline).\n"
    . "\\item Paste the week's \\texttt{dashboard.json} into \\emph{Data (JSON)}, then \\emph{Apply}.\n"
    . "\\item Tick the box on the tiles to say; \\emph{Copy statement} gives the round-robin text.\n"
    . "\\item Ctrl-P, Save as PDF: one landscape page for the report.\n"
    . "\\end{enumerate}\n";
$t .= "\\head{Collecting the numbers}\n{\\footnotesize\\ttfamily\n"
    . "perl bin/status-metrics.pl init \\textbackslash\\\\\\hspace*{1em}--config metrics.json --xmi legacy.xmi --reqif export.reqif\\\\[1pt]\n"
    . "perl bin/status-metrics.pl collect \\textbackslash\\\\\\hspace*{1em}--config metrics.json --history history.jsonl\\\\[1pt]\n"
    . "perl bin/status-metrics.pl report \\textbackslash\\\\\\hspace*{1em}--config metrics.json --history history.jsonl --out report\\par}\n"
    . "\\vspace{3pt}{\\small \\texttt{init} once (freezes the denominators), \\texttt{collect} daily, \\texttt{report} weekly: "
    . "\\texttt{status-weekly.md}, \\texttt{status-daily.csv}, \\texttt{dashboard.json}. Help: \\texttt{perl agile.pl help status-metrics}.}\\par\n";
$t .= "\\head{More}\n{\\small Definitions and collection methods: \\texttt{docs/STATUS-METRICS.html}. The worked example, day by day "
    . "(stand-ups, burn-downs, funding): \\texttt{docs/HALBERD.pdf}.\\par}\n";
$t .= "\\end{multicols}\n\\end{document}\n";

open my $fh, '>:encoding(UTF-8)', $o{tex} or die "cannot write $o{tex}: $!\n";
print $fh $t; close $fh or die "cannot write $o{tex}: $!\n";
print "wrote $o{tex}\n";

if ($o{pdf}) {
    require File::Temp; require File::Copy;
    my $tmp = File::Temp::tempdir(CLEANUP => 1);
    File::Copy::copy($o{tex}, "$tmp/qrg.tex") or die "cannot copy $o{tex}: $!\n";
    my $log = `cd "$tmp" && latexmk -xelatex -interaction=nonstopmode -halt-on-error qrg.tex 2>&1`;
    -f "$tmp/qrg.pdf" && $? == 0 or die "latexmk failed:\n" . join("\n", (split /\n/, $log)[-25 .. -1]) . "\n";
    my ($np) = slurp("$tmp/qrg.log") =~ /Output written on .*?\((\d+) page/;
    die "the card runs to $np pages; it must fit one sheet (2 pages)\n" if ($np // 0) > 2;
    (my $pdf = $o{tex}) =~ s/\.tex$/.pdf/;
    File::Copy::copy("$tmp/qrg.pdf", $pdf) or die "cannot write $pdf: $!\n";
    print "wrote $pdf ($np pages)\n";
}
